[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = "0.38"
async-trait = "0.1.86"
chrono = { version = "0.4", features = ["serde"] }
clickhouse = { version = "0.13", features = ["uuid", "time"] }
envy = "0.4.2"
futures = "0.3"
metrics = "0.24"
parking_lot = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.15"
serde_json = "1.0"
thiserror = "2.0"
time = { version = "0.3.37", features = ["serde"] }
tokio = { version = "1.43", features = ["full"] }
tokio-tungstenite = "0.26.1"
tracing = "0.1"
unicode-normalization = "0.1.24"
url = "2.5.4"
uuid = { version = "1.13", features = ["v4", "serde"] }

[dev-dependencies]
mockall = "0.13"
pretty_assertions = "1.4"
tokio-test = "0.4"
